name             "drupal-frontend"
maintainer       "Tim Whitney"
maintainer_email "tim.d.whitney@gmail.com"
license          "Apache 2.0"
description      "Installs/configures frontend tools"
version          "0.2.1"
recipe           "skeleton::default", "Installs/configures nodejs, bundler, bower, grunt"
